org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
android.useAndroidX=true
android.nonTransitiveRClass=true
android.aapt2FromMavenOverride=C:/Users/Sim/AppData/Local/Android/Sdk/build-tools/34.0.0/aapt2.exe
android.aapt2DaemonModeEnabled=false
